// Targeted ART V2B checks and manifest. No engine or gameplay execution.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert');
const sharp=require('C:/Users/AKNATE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const HERE=__dirname,REPO=path.resolve(HERE,'../..'),read=n=>JSON.parse(fs.readFileSync(path.join(HERE,n))),write=(n,x)=>fs.writeFileSync(path.join(HERE,n),JSON.stringify(x,null,2)+'\n'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const provenance='Generated with the available built-in ImageGen; exact underlying image model/quality tier was not exposed by the tool.';
const checks=[];function check(name,pass,evidence){checks.push({name,pass:!!pass,evidence});assert(pass,name);}
function luminance(rgb){const v=rgb.map(c=>{c/=255;return c<=.04045?c/12.92:((c+.055)/1.055)**2.4;});return .2126*v[0]+.7152*v[1]+.0722*v[2];}
async function main(){const items=read('export_report.json'),prompts=read('prompts.json'),layout=read('review_layout.json'),entries=[],metrics={},audit=[];
 check('exact_16_pngs',items.length===16&&fs.readdirSync(path.join(REPO,'assets/art_v2b')).filter(n=>n.endsWith('.png')).length===16,16);
 for(let index=0;index<items.length;index++){const it=items[index],file=path.join(REPO,it.file),bytes=fs.readFileSync(file),m=await sharp(bytes).metadata(),{data}=await sharp(bytes).ensureAlpha().raw().toBuffer({resolveWithObject:true});
  check(it.name+'_format',m.width===it.width&&m.height===it.height&&m.channels===4&&m.hasAlpha&&m.depth==='uchar'&&m.space==='srgb'&&!!m.icc,{size:[m.width,m.height],mode:'RGBA8',profile:!!m.icc});
  const a=Buffer.alloc(m.width*m.height);let border=true,zeroRGB=true,nonzero=0;for(let y=0;y<m.height;y++)for(let x=0;x<m.width;x++){const i=y*m.width+x,k=i*4;a[i]=data[k+3];if(a[i])nonzero++;if((x<8||y<8||x>=m.width-8||y>=m.height-8)&&a[i])border=false;if(!a[i]&&(data[k]||data[k+1]||data[k+2]))zeroRGB=false;}
  check(it.name+'_alpha',border&&nonzero>0&&zeroRGB&&sha(a)===it.alphaSha256,{outer8pxTransparent:border,transparentRGBZero:zeroRGB,alphaSha256:sha(a)});
  check(it.name+'_integrity',sha(bytes)===it.sha256&&sha(fs.readFileSync(path.join(HERE,it.source)))===it.sourceSha256,'Output and source SHA-256 match export report');
  check(it.name+'_ascii',/^[a-z0-9_]+\.png$/.test(it.filename),it.filename);
  if(it.textSafeRect){const [x,y,w,h]=it.textSafeRect;let min=255;for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)min=Math.min(min,a[yy*m.width+xx]);check(it.name+'_text_safe',w>0&&h>0&&min>=250,{rect:it.textSafeRect,minAlpha:min});}
  if(it.name==='board_frame'||it.name==='button_selected_frame'){const rect=it.name==='board_frame'?it.boardGridSafeRect:{left:128,top:48,width:512,height:96};let max=0;for(let y=rect.top;y<rect.top+rect.height;y++)for(let x=rect.left;x<rect.left+rect.width;x++)max=Math.max(max,a[y*m.width+x]);check(it.name+'_open_center',max===0,{rect,maxAlpha:max});}
  const rect=it.textSafeRect||[Math.floor(m.width*.4),Math.floor(m.height*.4),Math.floor(m.width*.2),Math.floor(m.height*.2)];
  const gray=await sharp(file).extract({left:rect[0],top:rect[1],width:rect[2],height:rect[3]}).grayscale().removeAlpha().raw().toBuffer();let sum=0;for(const v of gray)sum+=v;const mean=sum/gray.length;let variance=0;for(const v of gray)variance+=(v-mean)**2;
  const rgb=await sharp(file).extract({left:rect[0],top:rect[1],width:rect[2],height:rect[3]}).removeAlpha().raw().toBuffer(),rgbMean=[0,0,0];for(let i=0;i<rgb.length;i+=3)for(let c=0;c<3;c++)rgbMean[c]+=rgb[i+c];for(let c=0;c<3;c++)rgbMean[c]/=rgb.length/3;
  const textRGB=it.name==='button_primary'?[255,244,218]:[57,43,27],lum=luminance(rgbMean),tl=luminance(textRGB),contrast=(Math.max(lum,tl)+.05)/(Math.min(lum,tl)+.05);
  metrics[it.name]={grayMean:Number(mean.toFixed(2)),grayStd:Number(Math.sqrt(variance/gray.length).toFixed(2)),meanTextContrast:Number(contrast.toFixed(2)),textRGB,note:'Mean face metric supports visual inspection; not a worst-pixel or accessibility certification.'};
  entries.push({...it,cornerScale:it.name==='board_frame'?.70:1,alphaNote:it.sourceHasAlpha?'Generated alpha retained for master; detached dust removed; shared state alpha where documented':'Generated neutral background extracted; final alpha normalized and verified',usage:it.name==='board_frame'?'Uniformly scale square frame; align playfield to boardGridSafeRect':it.name==='button_selected_frame'?'Overlay on same button canvas and transform; empty center':'Blank UI texture; separate real text/icon nodes above',review:false});
  const s=Math.min(132/it.width,120/it.height),sample=await sharp(file).resize(Math.round(it.width*s),Math.round(it.height*s)).png().toBuffer();const x=24+index%4*304,y=36+Math.floor(index/4)*170;
  for(let b=0;b<2;b++){const tile=await sharp({create:{width:140,height:132,channels:4,background:b?'#29251f':'#f0e7d4'}}).composite([{input:sample,left:Math.round((140-it.width*s)/2),top:Math.round((132-it.height*s)/2)}]).png().toBuffer();audit.push({input:tile,left:x+b*144,top:y});}
 }
 for(const [name,master]of [['button_secondary','button_primary'],['button_disabled','button_primary'],['chapter_card_locked','chapter_card_open'],['chapter_card_completed','chapter_card_open'],['collection_card_unknown','collection_card_known']])check(name+'_shared_state_alpha',items.find(i=>i.name===name).alphaSha256===items.find(i=>i.name===master).alphaSha256,master);
 const p=metrics.button_primary.grayMean,s=metrics.button_secondary.grayMean,d=metrics.button_disabled.grayMean;check('button_grayscale_states',s-d>=25&&d-p>=25,{primary:p,disabled:d,secondary:s,minimumGap:Math.min(s-d,d-p)});
 check('primary_secondary_text_contrast',metrics.button_primary.meanTextContrast>=4.5&&metrics.button_secondary.meanTextContrast>=4.5,{primary:metrics.button_primary.meanTextContrast,secondary:metrics.button_secondary.meanTextContrast});
 check('board_pitch_mobile',layout.gameplay.board.cellPitch>=48&&layout.gameplay.board.cellPitch<=64,layout.gameplay.board.cellPitch);
 check('menu_structure',layout.menu.actions.join('|')==='Играть|Экспедиции|Коллекция|Настройки',layout.menu.actions);
 check('prompts_complete',prompts.attempts.length===16&&items.every(i=>prompts.attempts.some(a=>a.asset===i.filename&&a.status==='succeeded'&&a.toolArguments.prompt&&a.toolArguments.referenced_image_paths.every(p=>fs.existsSync(p)))),16);
 const v2a=JSON.parse(fs.readFileSync(path.join(REPO,'art_review/art_v2a/manifest.json'))).entries;check('v2a_assets_and_reviews_unchanged',v2a.every(i=>sha(fs.readFileSync(path.join(REPO,i.file)))===i.sha256),v2a.length+' accepted V2A hashes unchanged');
 const reviews={ui_family_overview:[1280,1240],readability_48px:[1200,1260],grayscale_readability:[1200,1260],gameplay_mockup_ui_only:[720,1280],menu_mockup_ui_only:[720,1280]};
 for(const[name,size]of Object.entries(reviews)){const file=path.join(HERE,name+'.png'),bytes=fs.readFileSync(file),m=await sharp(bytes).metadata();check(name+'_size',m.width===size[0]&&m.height===size[1],size);entries.push({filename:name+'.png',file:'art_review/art_v2b/'+name+'.png',purpose:name,width:size[0],height:size[1],family:'review',state:'review_composite',alphaNote:'Opaque review background; not a production sprite',production:false,review:true,sha256:sha(bytes)});}
 await sharp({create:{width:1250,height:730,channels:4,background:'#625744'}}).composite(audit).png().toFile(path.join(HERE,'alpha_edges_review.png'));
 const grayRGB=await sharp(path.join(HERE,'grayscale_readability.png')).removeAlpha().toColourspace('srgb').raw().toBuffer();let neutral=true;for(let i=0;i<grayRGB.length;i+=3)if(grayRGB[i]!==grayRGB[i+1]||grayRGB[i]!==grayRGB[i+2]){neutral=false;break;}check('grayscale_neutral',neutral,'All RGB channels equal');
 check('integration_guard',fs.existsSync(path.join(REPO,'assets/art_v2b/.gdignore'))&&fs.existsSync(path.join(HERE,'.gdignore')),'Production and review directories excluded from Godot import');
 const visual=[['style','PASS','One reference-derived warm sandstone family, restrained chips, clipped corners and upper-left illumination.'],['frame','PASS','Clean continuous ring, reduced border via nine-region normalization, no ornament or blocked board corners.'],['button_states','PASS','Dark green primary, pale sandstone secondary and medium gray-beige disabled remain distinct in grayscale and at48/64px visible body height.'],['card_siblings','PASS','Tray, chapter and collection share recessed rim language. State accents supplement separate runtime labels/icons.'],['text_areas','PASS','Blank production faces; separate Russian review text remains readable with generous center space.'],['composites','PASS','V1 menu action order and gameplay control/information structure retained; no background generation, lighter helper text and counters.']].map(([gate,status,evidence])=>({gate,status,evidence}));
 const limitations=['Static agent art review, not user testing or runtime Godot verification.','Nine-region resizing is demonstrated offline; actual engine filtering, theme states and minimum layout sizes need verification during integration.','Known/unknown and open/completed card material signals should be supplemented by separate labels/icons for accessibility; no such glyphs are baked into these sprites.','Menu discovery motif reuses the V2A target center for review; it is not a new approved logo or production background.'];
 write('manifest.json',{schemaVersion:1,milestone:'ART V2B',status:'production_candidate_ready_for_user_review',provenance,pathBase:'repository root',style:'Light Sandstone Courtyard',entries,reviewLayout:layout,auxiliaryReview:{file:'art_review/art_v2b/alpha_edges_review.png',size:[1250,730],note:'16 assets in manifest order; light then dark background pairs, supplementary edge audit'},integration:{performed:false,notes:'Texture art only. Use real Godot Control nodes for persistent UI and separate labels/icons. Preserve state canvas/pivot and ninePatchMargins; frame uses boardGridSafeRect.'}});
 write('verification.json',{status:'PASS_OFFLINE_PRODUCTION_CANDIDATE',provenance,automated:{passed:checks.length,total:checks.length,checks},metrics,visualReview:{reviewer:'Codex agent',gates:visual},limitations,integration:{godotRun:false,gameplayOrScenesEdited:false,v2aHashesUnchanged:true}});
 prompts.status='final_exports_verified_production_candidate';prompts.provenance=provenance;prompts.postprocessing={script:'export_pack.cjs',sourcesPreserved:true,generatedAlphaSources:items.filter(i=>i.sourceHasAlpha).map(i=>i.name),neutralMatteExtractedFor:items.filter(i=>!i.sourceHasAlpha).map(i=>i.name),steps:['Preserve generated master alpha; remove detached alpha dust','Flood neutral exterior and board/selection center when source lacks alpha; one-source-pixel contraction','Nine-region aspect normalization with uniformly scaled corners; board corner scale0.70 for calmer border','Exact shared alpha for three button states, three chapter states, two collection states','RGBA8 sRGB ICC PNG with transparent margins; no new drawn material illustration'],paletteCorrection:'none'};write('prompts.json',prompts);
 console.log(JSON.stringify({status:'PASS',checks:checks.length,buttonGrayscale:{primary:p,disabled:d,secondary:s},buttonTextContrast:{primary:metrics.button_primary.meanTextContrast,secondary:metrics.button_secondary.meanTextContrast},boardPitch:layout.gameplay.board.cellPitch},null,2));
}
main().catch(e=>{console.error(e);process.exit(1)});
